import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ShareButtons } from "@/components/share-buttons";
import { publicUrl } from "@/lib/config";
import { createClient } from "@/lib/supabase/server";
import { SUPABASE_CONFIGURED } from "@/lib/supabase/shared";

type Params = { id: string };

export const dynamic = "force-dynamic";

/**
 * One beg, at its own URL.
 *
 * This is the page a shared link opens. The image beside it is generated by
 * `opengraph-image.tsx` in this folder, so a post to X or Telegram shows the
 * words rather than a bare URL — the image and the link are the same resource,
 * which is why nothing has to be uploaded or stored.
 */
async function getBeg(id: string) {
  if (!SUPABASE_CONFIGURED || !/^[0-9a-f-]{36}$/i.test(id)) return null;

  const sb = await createClient();
  const { data, error } = await sb
    .from("begs")
    .select("id, body, goal, created_at, profiles!inner(username, display_name, avatar_url)")
    .eq("id", id)
    .maybeSingle<{
      id: string;
      body: string;
      goal: string | null;
      created_at: string;
      profiles: { username: string; display_name: string | null; avatar_url: string | null };
    }>();

  // `error` is read rather than caught — supabase-js does not throw, so a
  // swallowed error here would render as "this beg does not exist" for a beg
  // that plainly does.
  if (error) return null;
  return data;
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { id } = await params;
  const beg = await getBeg(id);

  if (!beg) return { title: "Beg not found" };

  const who = beg.profiles.display_name ?? `@${beg.profiles.username}`;
  const url = publicUrl(`/beg/${beg.id}`);

  return {
    title: `${who} is begging`,
    description: beg.body,
    openGraph: {
      title: `${who} is begging`,
      description: beg.body,
      url,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: `${who} is begging`,
      description: beg.body,
    },
  };
}

export default async function BegPage({ params }: { params: Promise<Params> }) {
  const { id } = await params;
  const beg = await getBeg(id);

  if (!beg) notFound();

  const who = beg.profiles.display_name ?? `@${beg.profiles.username}`;
  const url = publicUrl(`/beg/${beg.id}`);

  return (
    <div className="mx-auto grid max-w-[560px] gap-6 px-5 py-10">
      <header className="flex items-center gap-3">
        {beg.profiles.avatar_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={beg.profiles.avatar_url} alt="" className="size-12 rounded-full object-cover" />
        ) : (
          <div className="grid size-12 place-items-center rounded-full bg-beg-lime text-xl font-extrabold text-beg-bg">
            {who[0]?.toUpperCase() ?? "?"}
          </div>
        )}
        <div>
          <div className="font-bold text-beg-ink">{who}</div>
          <Link href={`/${beg.profiles.username}`} className="text-[13px] text-beg-dim hover:text-beg-ink">
            @{beg.profiles.username}
          </Link>
        </div>
      </header>

      {/* The ask itself, given the most room on the page. */}
      <p className="text-[clamp(24px,5vw,34px)] font-extrabold leading-[1.15] tracking-[-.03em] text-beg-ink">
        {beg.body}
      </p>

      <ShareButtons url={url} text={`${who} is begging: ${beg.body}`} />

      <Link
        href={`/${beg.profiles.username}`}
        className="rounded-full border-[1.5px] border-beg-line p-4 text-center font-bold text-beg-ink transition-colors hover:border-beg-lime"
      >
        Send {who.split(" ")[0]} some $BEG
      </Link>

      <p className="text-center text-[12px] text-beg-dim">
        BegFi never holds funds. A send goes straight from your wallet to theirs.
      </p>
    </div>
  );
}
