import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ShareButtons } from "@/components/share-buttons";
import { publicUrl } from "@/lib/config";
import { formatAmount } from "@/lib/erc20";
import { createClient } from "@/lib/supabase/server";
import { SUPABASE_CONFIGURED } from "@/lib/supabase/shared";

type Params = { id: string };

export const dynamic = "force-dynamic";

/**
 * One beg, at its own URL.
 *
 * This is the page a shared link opens. The image beside it is generated by
 * `opengraph-image.tsx` in this folder, so a post to X or Telegram shows the
 * words rather than a bare URL — the image and the link are the same resource.
 *
 * PROGRESS IS AN AGGREGATE, fetched through `received_since`. A visitor cannot
 * read `transfers` — the RLS policy allows a row only to the two addresses
 * involved, deliberately, so the sender graph is not public — so a page that
 * summed transfers itself would show every logged-out visitor a confident zero.
 * The function returns one number and nothing else.
 */
async function getBeg(id: string) {
  if (!SUPABASE_CONFIGURED || !/^[0-9a-f-]{36}$/i.test(id)) return null;

  const sb = await createClient();
  const { data, error } = await sb
    .from("begs")
    .select("id, body, goal, created_at, profiles!inner(username, display_name, avatar_url, wallet_address)")
    .eq("id", id)
    .maybeSingle<{
      id: string;
      body: string;
      goal: string | null;
      created_at: string;
      profiles: {
        username: string;
        display_name: string | null;
        avatar_url: string | null;
        wallet_address: string;
      };
    }>();

  // `error` is read rather than caught — supabase-js does not throw, so a
  // swallowed error here would render "this beg does not exist" for a beg that
  // plainly does.
  if (error || !data) return null;

  // What has arrived since this beg was written. A failure to read it must not
  // hide the beg, so it degrades to zero and the page says so.
  let raised = 0n;
  let progressKnown = true;

  if (data.goal) {
    const { data: sum, error: sumError } = await sb.rpc("received_since", {
      p_wallet: data.profiles.wallet_address,
      p_since: data.created_at,
    });

    if (sumError || sum === null) {
      progressKnown = false;
    } else {
      try {
        raised = BigInt(sum as string);
      } catch {
        progressKnown = false;
      }
    }
  }

  return { ...data, raised, progressKnown };
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { id } = await params;
  const beg = await getBeg(id);

  if (!beg) return { title: "Beg not found" };

  const who = beg.profiles.display_name ?? `@${beg.profiles.username}`;
  const url = publicUrl(`/beg/${beg.id}`);

  return {
    title: `${who} is begging`,
    description: beg.body,
    openGraph: {
      title: `${who} is begging`,
      description: beg.body,
      url,
      type: "article",
    },
    twitter: { card: "summary_large_image", title: `${who} is begging`, description: beg.body },
  };
}

export default async function BegPage({ params }: { params: Promise<Params> }) {
  const { id } = await params;
  const beg = await getBeg(id);

  if (!beg) notFound();

  const who = beg.profiles.display_name ?? `@${beg.profiles.username}`;
  const url = publicUrl(`/beg/${beg.id}`);

  const goal = beg.goal ? BigInt(beg.goal) : null;
  const filled = goal !== null && beg.raised >= goal;
  // Basis points, so the bar and the percentage cannot disagree, and no float
  // ever touches a token amount.
  const pct = goal && goal > 0n ? Number((beg.raised * 10_000n) / goal) / 100 : 0;

  return (
    <div className="safe-x mx-auto grid max-w-[560px] gap-6 py-10">
      <header className="flex items-center gap-3">
        {beg.profiles.avatar_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={beg.profiles.avatar_url} alt="" className="size-12 rounded-full object-cover" />
        ) : (
          <div className="grid size-12 place-items-center rounded-full bg-beg-lime text-xl font-extrabold text-beg-ink">
            {who[0]?.toUpperCase() ?? "?"}
          </div>
        )}
        <div>
          <div className="font-bold text-beg-ink">{who}</div>
          <Link href={`/${beg.profiles.username}`} className="text-[13px] text-beg-dim hover:text-beg-ink">
            @{beg.profiles.username}
          </Link>
        </div>
      </header>

      {/* The ask itself, given the most room on the page. */}
      <p className="text-[clamp(24px,5vw,34px)] font-extrabold leading-[1.15] tracking-[-.03em] text-beg-ink">
        {beg.body}
      </p>

      {/* Progress, when a target was set. */}
      {goal !== null && goal > 0n ? (
        <section className="card grid gap-2">
          <div className="flex items-baseline justify-between gap-3">
            <span className="text-[13px] text-beg-dim">Raised</span>
            <span className="text-[13px] text-beg-dim">Goal {formatAmount(goal)} $BEG</span>
          </div>

          <div className="text-[28px] font-extrabold tracking-[-.04em] text-beg-ink">
            {formatAmount(beg.raised)} $BEG
          </div>

          <div
            className="h-3 overflow-hidden rounded-full bg-beg-bg"
            role="progressbar"
            aria-valuenow={Math.min(100, Math.round(pct))}
            aria-valuemin={0}
            aria-valuemax={100}
            aria-label="Progress toward the goal"
          >
            <div
              className="h-full rounded-full bg-beg-lime"
              style={{ width: `${Math.min(100, pct)}%` }}
            />
          </div>

          <p className="text-[12px] text-beg-dim">
            {filled
              ? "Filled. Anything more still lands in their wallet."
              : `${pct.toFixed(1)}% of the way there`}
          </p>

          {/*
            Saying this plainly matters more than it looks. The number comes from
            the indexer, which on a Hobby plan runs once a day, so a send made a
            minute ago is genuinely not in it yet — and a page that implied
            otherwise would look broken to the person who just sent.
          */}
          {!beg.progressKnown ? (
            <p className="text-[12px] text-beg-dim">
              Couldn&apos;t read the total just now. That&apos;s a problem reaching the chain, not a
              zero.
            </p>
          ) : (
            <p className="text-[12px] text-beg-dim">
              Counted from confirmed transfers. A send can take a little while to appear here.
            </p>
          )}
        </section>
      ) : null}

      <ShareButtons url={url} text={beg.body} />

      <Link
        href={`/${beg.profiles.username}`}
        className="rounded-full bg-beg-lime p-4 text-center text-[17px] font-bold text-beg-ink"
      >
        Send {who.split(" ")[0]} some $BEG
      </Link>

      <p className="text-center text-[12px] text-beg-dim">
        BegFi never holds funds. A send goes straight from your wallet to theirs.
      </p>
    </div>
  );
}
